import Head from "next/head";
import React, { useEffect, useState } from "react";
import axios from "axios";
import AOS from "aos";
import "aos/dist/aos.css";
import { FaTools, FaShieldAlt, FaCog } from "react-icons/fa";

const categoryIcons = {
  "Genel": <FaTools />,
  "Güvenlik": <FaShieldAlt />,
  "Özelleştirme": <FaCog />
};

const Commands = ({ datas }) => {
  const [data, setData] = useState([]);
  const [search, setSearch] = useState("");

  useEffect(() => {
    async function fetchData() {
      const result = await axios.get("/api/data");
      setData(result.data);
    }

    fetchData();
    AOS.init({ duration: 600, easing: 'ease-in-out', once: true });
  }, []);

  const filter = data.filter((data) => {
    return data.title.toLowerCase().includes(search.toLowerCase());
  });

  const categories = [...new Set(filter.map(item => item.category))];

  return (
    <>
      <Head>
        <title>PlusBot - Commands</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto p-6">
        <div className="flex flex-col gap-6">
          <div className="text-center">
            <h1 className="text-4xl font-bold text-white mb-4" data-aos="fade-down">Komutlar</h1>
            <input
              type="text"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full bg-gray-700 p-3 rounded-lg placeholder:text-gray-400 outline-none border-2 border-gray-600 focus:border-blue-500 text-white transition duration-300"
              placeholder="Komut Ara"
              data-aos="fade-down"
              data-aos-delay="100"
            />
          </div>
          <div className="h-[500px] overflow-y-scroll scrollbar-thumb-gray-300 scrollbar-track-gray-100" data-aos="fade-up">
            {categories.map(category => (
              <div key={category} className="mb-6">
                <h2 className="text-2xl font-semibold text-yellow-300 mb-4 flex items-center gap-2" data-aos="fade-right">
                  {categoryIcons[category]} {category}
                </h2>
                <ul className="flex flex-col gap-4">
                  {filter.filter(item => item.category === category).map((data) => (
                    <li
                      key={data.id}
                      className="relative select-none bg-gradient-to-r from-gray-700 to-gray-800 w-full rounded-lg p-4 text-white cursor-pointer hover:bg-gray-900 flex items-center gap-4 shadow-lg transform transition-transform duration-300 hover:scale-105"
                      data-aos="fade-up"
                      data-aos-delay="200"
                    >
                      <span className="bg-gray-900 p-3 rounded-lg text-yellow-300 text-lg font-bold">{data.id}</span>
                      <div>
                        <h2 className="text-xl font-bold">{data.title}</h2>
                        <p className="text-gray-400 mt-2">{data.desc}</p>
                      </div>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
          <div className="mt-10 bg-gray-800 p-6 rounded-lg shadow-lg" data-aos="fade-up">
            <h2 className="text-3xl font-bold text-white text-center mb-6">Hakkında</h2>
            <p className="text-gray-400 text-center">
              PlusBot, sunucunuzu yönetmenize yardımcı olan güçlü bir Discord botudur. Gelişmiş komutlar ve özellikler ile sunucunuzu daha iyi hale getirin.
            </p>
          </div>
          <div className="mt-10 bg-gray-800 p-6 rounded-lg shadow-lg" data-aos="fade-up">
            <h2 className="text-3xl font-bold text-white text-center mb-6">Sıkça Sorulan Sorular</h2>
            <div className="text-gray-400">
              <div className="mb-4">
                <h3 className="text-xl font-semibold text-yellow-300">PlusBot nedir?</h3>
                <p>PlusBot, sunucunuzu yönetmenize yardımcı olan güçlü bir Discord botudur.</p>
              </div>
              <div className="mb-4">
                <h3 className="text-xl font-semibold text-yellow-300">Nasıl kurulur?</h3>
                <p>PlusBot'u sunucunuza eklemek için "Sunucuna Ekle" butonuna tıklayın ve talimatları izleyin.</p>
              </div>
              <div className="mb-4">
                <h3 className="text-xl font-semibold text-yellow-300">Hangi özelliklere sahiptir?</h3>
                <p>PlusBot, gelişmiş güvenlik, özelleştirilebilir komutlar ve daha birçok özellik sunar.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Commands;
